### ISSUE TITLE
Javascript, Mocha, chai, sinon reporting Green when should be Amber

### ISSUE THREAD

**Issue by sebrose** [JonJagger/cyber-dojo#70]
This output caused a Green traffic light, but should have been Amber:

FizzBuzz

    1) should return fizz for multiples of 3
 
 
  0 passing (32ms)
  1 failing
 
  1) FizzBuzz should return fizz for multiples of 3:
     TypeError: undefined is not a function
      at Context.<anonymous> (fizzbuzzTest.js:12:27)

**Comment by JonJagger** [comment]
Hi Seb,
could you send me the source files that produced it please.
Thanks
Jon

On Wed, Oct 21, 2015 at 3:22 PM, Seb Rose <notifications@github.com> wrote:

> This output caused a Green traffic light, but should have been Amber:
>
> FizzBuzz
>
> 1) should return fizz for multiples of 3
>
>
>
> 0 passing (32ms)
> 1 failing
>
> 1) FizzBuzz should return fizz for multiples of 3:
> TypeError: undefined is not a function
> at Context. (fizzbuzzTest.js:12:27)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JonJagger/cyber-dojo/issues/70>.
>



-- 
Cyber-Dojo : a place to practise the collaborative game called software
development.
Server at http://www.cyber-dojo.org
Open-sourced at http://github.com/JonJagger/cyberdojo
Explained at http://jonjagger.blogspot.co.uk/p/cyber-dojo_2380.html
Video of Roman Numerals kata in Ruby at https://vimeo.com/104548135

**Comment by sebrose** [comment]
Here you are. I was going to have a look at this myself, but I need to
remind myself where the regex of the output is chosen.


On Wed, 21 Oct 2015, at 03:55 PM, Jon Jagger wrote:
> Hi Seb,
>
could you send me the source files that produced it please.
>
Thanks
>
Jon
>
>
On Wed, Oct 21, 2015 at 3:22 PM, Seb Rose <notifications@github.com> wrote:
>
>
> This output caused a Green traffic light, but should have been Amber:
>
>
>
> FizzBuzz
>
>
>
> 1) should return fizz for multiples of 3
>
>
>
>
>
>
>
>  passing (32ms)
>
> 1 failing
>
>
>
> 1) FizzBuzz should return fizz for multiples of 3:
>
> TypeError: undefined is not a function
>
> at Context. (fizzbuzzTest.js:12:27)
>
>
>
> —
>
> Reply to this email directly or view it on GitHub
>
> <https://github.com/JonJagger/cyber-dojo/issues/70>.
>
>
>
>
>
>
-- 
> 
Cyber-Dojo : a place to practise the collaborative game called software
> 
development.
> 
Server at http://www.cyber-dojo.org
> 
Open-sourced at http://github.com/JonJagger/cyberdojo
> 
Explained at http://jonjagger.blogspot.co.uk/p/cyber-dojo_2380.html
> 
Video of Roman Numerals kata in Ruby at https://vimeo.com/104548135
> —
> Reply to this email directly or view it on GitHub[1]. 


>  
 
--
The Cucumber for Java Book - Seb Rose, Matt Wynne & Aslak Hellesøy
Now available from the Pragmatic Press - https://pragprog.com/book/srjcuc/the-cucumber-for-java-book
 


Links:

  1. https://github.com/JonJagger/cyber-dojo/issues/70#issuecomment-149922981

**Comment by JonJagger** [comment]
Fixed. Thanks

**Comment by JonJagger** [comment]
By the way, the regex happens here
https://github.com/JonJagger/cyber-dojo/blob/master/app/lib/output_colour.rb

And the tests are here
https://github.com/JonJagger/cyber-dojo/blob/master/test/app_lib/test_output_colour.rb


On Wed, Oct 21, 2015 at 6:41 PM, Seb Rose <notifications@github.com> wrote:

> Here you are. I was going to have a look at this myself, but I need to
> remind myself where the regex of the output is chosen.
>
>
> On Wed, 21 Oct 2015, at 03:55 PM, Jon Jagger wrote:
> > Hi Seb,
> >
> could you send me the source files that produced it please.
> >
> Thanks
> >
> Jon
> >
> >
> On Wed, Oct 21, 2015 at 3:22 PM, Seb Rose <notifications@github.com>
> wrote:
> >
> >
> > This output caused a Green traffic light, but should have been Amber:
> >
> >
> >
> > FizzBuzz
> >
> >
> >
> > 1) should return fizz for multiples of 3
> >
> >
> >
> >
> >
> >
> >
> > passing (32ms)
> >
> > 1 failing
> >
> >
> >
> > 1) FizzBuzz should return fizz for multiples of 3:
> >
> > TypeError: undefined is not a function
> >
> > at Context. (fizzbuzzTest.js:12:27)
> >
> >
> >
> > —
> >
> > Reply to this email directly or view it on GitHub
> >
> > <https://github.com/JonJagger/cyber-dojo/issues/70>.
> >
> >
> >
> >
> >
> >
> --
> >
> Cyber-Dojo : a place to practise the collaborative game called software
> >
> development.
> >
> Server at http://www.cyber-dojo.org
> >
> Open-sourced at http://github.com/JonJagger/cyberdojo
> >
> Explained at http://jonjagger.blogspot.co.uk/p/cyber-dojo_2380.html
> >
> Video of Roman Numerals kata in Ruby at https://vimeo.com/104548135
> > —
> > Reply to this email directly or view it on GitHub[1].
>
>
> >
>
> --
> The Cucumber for Java Book - Seb Rose, Matt Wynne & Aslak Hellesøy
> Now available from the Pragmatic Press -
> https://pragprog.com/book/srjcuc/the-cucumber-for-java-book
>
>
>
> Links:
>
> 1.
> https://github.com/JonJagger/cyber-dojo/issues/70#issuecomment-149922981
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JonJagger/cyber-dojo/issues/70#issuecomment-149973525>
> .
>



-- 
Cyber-Dojo : a place to practise the collaborative game called software
development.
Server at http://www.cyber-dojo.org
Open-sourced at http://github.com/JonJagger/cyberdojo
Explained at http://jonjagger.blogspot.co.uk/p/cyber-dojo_2380.html
Video of Roman Numerals kata in Ruby at https://vimeo.com/104548135
