### ISSUE TITLE
Ruby shell script only allows one test file to be run

### ISSUE THREAD

**Issue by dpetersnews** [JonJagger/cyber-dojo#75]
The ruby shell script doesn't run all test files, only the first one it finds alphabetically.

**Comment by JonJagger** [comment]
Hi,
thanks for the comment.
Which ruby shell script?

**Comment by dpetersnews** [comment]
Here:
cyber-dojo/languages/Ruby2.1.3/MiniTest/cyber-dojo.sh

Calls ruby *test*.rb but will only ever run the first ruby file it has, if you subsequently created a second test ruby file, it will run that depending on which come first alphabetically it seems.

**Comment by JonJagger** [comment]
You are right. On the todo list.
Many thanks
