### ISSUE TITLE
command such as catalog is broken

### ISSUE THREAD

**Issue by whyzdev** [JonJagger/cyber-dojo#86]
Saw directory structure change and file move. Looks like missing start_points/ in
https://github.com/JonJagger/cyber-dojo/blob/d102e9ee73b8a5eeabfdd8bb9a183beb416d5dd5/app/docker/cyber-dojo.rb#L68

Please take a look. Sorry for not getting chance on a pull request. (Try quick fix in docker image on-the-fly is not straight forward for novice like me. Quickest I could think of is hack "docker run" to "docker exec" to try a change out, without deriving an images and make the change.)

Thanks,

**Comment by JonJagger** [comment]
Ach you are right. Fixed it.
Many thanks.
Jon
P.S. There is a readme.dev file in the root of the github repo which may be
helpful.



On Thu, May 5, 2016 at 5:07 AM, whyzdev <notifications@github.com> wrote:

> Saw directory structure change and file move. Looks like missing
> start_points/ in
>
> https://github.com/JonJagger/cyber-dojo/blob/d102e9ee73b8a5eeabfdd8bb9a183beb416d5dd5/app/docker/cyber-dojo.rb#L68
>
> Please take a look. Sorry for not getting chance on a pull request. (Try
> quick fix in docker image on-the-fly is not straight forward for novice
> like me. Quickest I could think of is hack "docker run" to "docker exec" to
> try a change out, without deriving an images and make the change.)
>
> Thanks,
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/JonJagger/cyber-dojo/issues/86>
>



-- 
Cyber-Dojo : a place to practise the collaborative game called software
development.
Server at http://www.cyber-dojo.org
Open-sourced at http://github.com/JonJagger/cyberdojo
Explained at http://jonjagger.blogspot.co.uk/p/cyber-dojo_2380.html
Video of Roman Numerals kata in Ruby at https://vimeo.com/104548135
